#############################################################################
# Makefile for building: zmp3
# Generated by qmake (2.00a) (Qt 4.1.3) on: Mo Jul 10 20:38:23 2006
# Project:  zmp3.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile zmp3.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
LEX           = flex
YACC          = yacc
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT  $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT  $(DEFINES)
LEXFLAGS      = 
YACCFLAGS     = -d
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Ifmodapi40412linux/api/inc -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lid3 fmodapi40412linux/api/lib/libfmodexp.so -lpthread -lQtGui -lQtNetwork -lQtCore
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		TLCDController.cpp \
		TLogic.cpp \
		TPushButtonSystem.cpp \
		TSong.cpp \
		TSoundSystem.cpp moc_TLCDController.cpp \
		moc_TLogic.cpp \
		moc_TPushButtonSystem.cpp
OBJECTS       = main.o \
		TLCDController.o \
		TLogic.o \
		TPushButtonSystem.o \
		TSong.o \
		TSoundSystem.o \
		moc_TLCDController.o \
		moc_TLogic.o \
		moc_TPushButtonSystem.o
DIST          = /usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		zmp3.pro
QMAKE_TARGET  = zmp3
DESTDIR       = 
TARGET        = zmp3

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: zmp3.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf
	$(QMAKE) -unix -o Makefile zmp3.pro
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile zmp3.pro

dist: 
	@$(CHK_DIR_EXISTS) ".tmp/zmp31.0.0" || $(MKDIR) ".tmp/zmp31.0.0"
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/zmp31.0.0/ && $(COPY_FILE) --parents TLCDController.h TLogic.h TPushButtonSystem.h TSong.h TSoundSystem.h .tmp/zmp31.0.0/ && $(COPY_FILE) --parents main.cpp TLCDController.cpp TLogic.cpp TPushButtonSystem.cpp TSong.cpp TSoundSystem.cpp .tmp/zmp31.0.0/ && (cd `dirname .tmp/zmp31.0.0` && $(TAR) zmp31.0.0.tar zmp31.0.0 && $(COMPRESS) zmp31.0.0.tar) && $(MOVE) `dirname .tmp/zmp31.0.0`/zmp31.0.0.tar.gz . && $(DEL_FILE) -r .tmp/zmp31.0.0


yaccclean:
lexclean:
clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


/usr/bin/moc-qt4:
	(cd "$(QTDIR)/src/tools/moc" && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_TLCDController.cpp moc_TLogic.cpp moc_TPushButtonSystem.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TLCDController.cpp moc_TLogic.cpp moc_TPushButtonSystem.cpp
moc_TLCDController.cpp: TLCDController.h \
		/usr/bin/moc-qt4
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TLCDController.h -o moc_TLCDController.cpp

moc_TLogic.cpp: TLCDController.h \
		TPushButtonSystem.h \
		TSoundSystem.h \
		TSong.h \
		TLogic.h \
		/usr/bin/moc-qt4
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TLogic.h -o moc_TLogic.cpp

moc_TPushButtonSystem.cpp: TPushButtonSystem.h \
		/usr/bin/moc-qt4
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TPushButtonSystem.h -o moc_TPushButtonSystem.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all:
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_image_collection_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

main.o: main.cpp TLogic.h \
		TLCDController.h \
		TPushButtonSystem.h \
		TSoundSystem.h \
		TSong.h

TLCDController.o: TLCDController.cpp TLCDController.h

TLogic.o: TLogic.cpp TLogic.h \
		TLCDController.h \
		TPushButtonSystem.h \
		TSoundSystem.h \
		TSong.h

TPushButtonSystem.o: TPushButtonSystem.cpp TPushButtonSystem.h

TSong.o: TSong.cpp TSong.h

TSoundSystem.o: TSoundSystem.cpp TSoundSystem.h \
		TSong.h

moc_TLCDController.o: moc_TLCDController.cpp 

moc_TLogic.o: moc_TLogic.cpp 

moc_TPushButtonSystem.o: moc_TPushButtonSystem.cpp 

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

